"use client";
import { FormEvent, useState } from "react";
import { Pencil, Plus, ShieldCheck, Trash2, X } from "lucide-react";
import { useRouter } from "next/navigation";

type AdminUser = { userId: string; name: string; email: string };
export function PlatformAdminManager({ admins }: { admins: AdminUser[] }) {
  const router = useRouter(); const [open, setOpen] = useState(false); const [editing, setEditing] = useState<AdminUser | null>(null); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setMessage(""); const body = Object.fromEntries(new FormData(event.currentTarget)); const response = await fetch("/api/admin/platform-admins", { method: editing ? "PATCH" : "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); const result = await response.json() as { error?: string }; setBusy(false); if (!response.ok) return setMessage(result.error ?? "Admin update failed"); setOpen(false); setEditing(null); setMessage(editing ? "Admin updated." : "Admin created."); router.refresh(); }
  async function remove(adminUser: AdminUser) { if (!confirm(`Remove administrator access from ${adminUser.name}?`)) return; setBusy(true); const response = await fetch("/api/admin/platform-admins", { method: "DELETE", headers: { "content-type": "application/json" }, body: JSON.stringify({ userId: adminUser.userId }) }); setBusy(false); if (!response.ok) return setMessage("Admin removal failed"); setMessage("Administrator access removed."); router.refresh(); }
  return <article className="glass mt-5 rounded-2xl p-6"><div className="flex items-start justify-between gap-4"><div><h2 className="flex items-center gap-2 font-semibold"><ShieldCheck className="size-5 text-[#1f7659]"/>Platform administrators</h2><p className="mt-1 text-xs text-[#71817c]">Only Nadeem (super admin) can add, edit, or remove administrators.</p></div><button onClick={() => { setEditing(null); setOpen(true); }} className="flex h-10 items-center gap-2 rounded-xl bg-[#164f3e] px-4 text-sm font-semibold text-white"><Plus className="size-4"/>Add admin</button></div>{message && <p className="mt-4 rounded-xl bg-[#e8f3ed] p-3 text-sm font-semibold text-[#1f7659]">{message}</p>}{(open || editing) && <form onSubmit={submit} className="mt-4 grid gap-3 rounded-2xl bg-white/70 p-4 md:grid-cols-4"><input type="hidden" name="userId" value={editing?.userId ?? ""}/><input name="name" required minLength={2} defaultValue={editing?.name} placeholder="Full name" className="h-11 rounded-xl border px-3"/><input name="email" required type="email" defaultValue={editing?.email} placeholder="Email" className="h-11 rounded-xl border px-3"/>{!editing && <input name="password" required type="password" minLength={8} placeholder="Temporary password" className="h-11 rounded-xl border px-3"/>}<div className="flex gap-2"><button disabled={busy} className="h-11 flex-1 rounded-xl bg-[#164f3e] px-4 text-sm font-semibold text-white">{editing ? "Save" : "Create admin"}</button><button type="button" onClick={() => { setOpen(false); setEditing(null); }} className="grid size-11 place-items-center rounded-xl border bg-white"><X className="size-4"/></button></div></form>}<div className="mt-4 space-y-2">{admins.map((adminUser) => <div key={adminUser.userId} className="flex items-center gap-3 rounded-xl bg-white/70 p-4"><div className="min-w-0 flex-1"><p className="font-semibold">{adminUser.name}</p><p className="text-xs text-[#71817c]">{adminUser.email}</p></div><button onClick={() => { setOpen(false); setEditing(adminUser); }} className="flex items-center gap-1 rounded-lg border bg-white px-3 py-2 text-xs font-semibold"><Pencil className="size-3"/>Edit</button><button disabled={busy} onClick={() => remove(adminUser)} className="flex items-center gap-1 rounded-lg border border-rose-200 bg-rose-50 px-3 py-2 text-xs font-semibold text-rose-700"><Trash2 className="size-3"/>Remove</button></div>)}{!admins.length && <p className="p-5 text-center text-sm text-[#71817c]">No additional platform administrators.</p>}</div></article>;
}
