"use client";

import { useMemo, useState } from "react";
import { Activity, BarChart3, MessageSquareText, Phone } from "lucide-react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Legend, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import type { DashboardDataset } from "./dashboard-shell";
import { DateRangePicker, type DateRangeValue } from "./date-range-picker";

const COLORS = ["#4f7df3", "#1f7659", "#d7f55b", "#e89b49", "#9b72cf", "#d45b6b"];
const successPattern = /success|book|resolved|qualified|completed/i;
const seconds = (value: string) => { const [m = 0, s = 0] = value.split(":").map(Number); return m * 60 + s; };
const percent = (part: number, total: number) => `${total ? Math.round(part / total * 100) : 0}%`;
type Props = { calls: DashboardDataset["calls"]; chats: DashboardDataset["chats"]; agents: DashboardDataset["agents"]; dateRange: DateRangeValue; onDateRangeChange: (value: DateRangeValue) => void; reportingMinimum: string };
type Datum = { name: string; value: number };

export function AnalyticsDashboard({ calls, chats, agents, dateRange, onDateRangeChange, reportingMinimum }: Props) {
  const [tab, setTab] = useState<"calls" | "chats">("calls");
  const [agentId, setAgentId] = useState("all");
  const [focused, setFocused] = useState<string | null>(null);
  const modelAgents = useMemo(() => agents.filter((a) => a.kind === (tab === "calls" ? "voice" : "chat")), [agents, tab]);
  const filteredCalls = useMemo(() => calls.filter((r) => agentId === "all" || r.agentId === agentId), [agentId, calls]);
  const filteredChats = useMemo(() => chats.filter((r) => agentId === "all" || r.agentId === agentId), [agentId, chats]);
  const successfulCalls = filteredCalls.filter((r) => successPattern.test(r.outcome));
  const successfulChats = filteredChats.filter((r) => successPattern.test(r.outcome));
  const pickup = filteredCalls.filter((r) => seconds(r.duration) > 0);
  const transferred = filteredCalls.filter((r) => /transfer/i.test(`${r.endReason} ${r.outcome}`));
  const voicemail = filteredCalls.filter((r) => /voicemail/i.test(`${r.endReason} ${r.outcome}`));
  const totalDuration = filteredCalls.reduce((sum, r) => sum + seconds(r.duration), 0);
  const avgDuration = filteredCalls.length ? Math.round(totalDuration / filteredCalls.length) : 0;
  const timeline = useMemo(() => {
    const buckets = new Map<string, { day: string; calls: number; chats: number; duration: number }>();
    for (const item of [...calls.map((r) => ({ type: "call", startedAt: r.startedAt, duration: seconds(r.duration), agentId: r.agentId })), ...chats.map((r) => ({ type: "chat", startedAt: r.startedAt, duration: 0, agentId: r.agentId }))]) {
      if (!item.startedAt || (agentId !== "all" && item.agentId !== agentId)) continue;
      const date = new Date(item.startedAt); const key = date.toISOString().slice(0, 10); const row = buckets.get(key) ?? { day: date.toLocaleDateString("en", { month: "short", day: "numeric" }), calls: 0, chats: 0, duration: 0 };
      if (item.type === "call") { row.calls += 1; row.duration += item.duration; } else row.chats += 1;
      buckets.set(key, row);
    }
    return [...buckets.entries()].sort(([a], [b]) => a.localeCompare(b)).map(([, r]) => ({ ...r, avgDuration: r.calls ? Math.round(r.duration / r.calls) : 0 }));
  }, [agentId, calls, chats]);
  const concurrency = useMemo(() => { const events = filteredCalls.flatMap((r) => { if (!r.startedAt) return []; const start = new Date(r.startedAt).getTime(); return [{ time: start, delta: 1 }, { time: start + seconds(r.duration) * 1000, delta: -1 }]; }).sort((a, b) => a.time - b.time || a.delta - b.delta); let active = 0; let peak = 0; for (const event of events) { active += event.delta; peak = Math.max(peak, active); } return peak; }, [filteredCalls]);
  const switchTab = (next: "calls" | "chats") => { setTab(next); setAgentId("all"); setFocused(null); };

  return <div className="space-y-4">
    <div className="glass rounded-2xl p-4"><div className="flex flex-col gap-4 xl:flex-row xl:items-center"><div className="flex gap-1 border-b xl:border-b-0"><Tab active={tab === "calls"} onClick={() => switchTab("calls")} icon={Phone}>Call Dashboard</Tab><Tab active={tab === "chats"} onClick={() => switchTab("chats")} icon={MessageSquareText}>Chat Dashboard</Tab></div><div className="flex flex-col gap-3 sm:flex-row xl:ml-auto"><DateRangePicker value={dateRange} onChange={onDateRangeChange} minimum={reportingMinimum} buttonLabel="Date Range" align="right"/><select aria-label="Filter analytics by agent" value={agentId} onChange={(e) => { setAgentId(e.target.value); setFocused(null); }} className="h-11 w-full min-w-64 rounded-xl border border-[#d9dee7] bg-white px-4 text-sm font-semibold outline-none focus:border-[#1f7659] sm:w-auto"><option value="all">All accessible {tab === "calls" ? "voice" : "chat"} agents</option>{modelAgents.map((a) => <option key={a.id} value={a.id}>{a.name}</option>)}</select></div></div></div>
    <div className="grid gap-4 md:grid-cols-3"><Metric label={tab === "calls" ? "Call latency" : "Chat response latency"} value="—" detail="Awaiting synchronized Retell latency data" icon={Activity}/><Metric label={tab === "calls" ? "Average call duration" : "Average messages"} value={tab === "calls" ? formatDuration(avgDuration) : String(filteredChats.length ? Math.round(filteredChats.reduce((s, r) => s + r.messages, 0) / filteredChats.length) : 0)} detail={tab === "calls" ? `${totalDuration}s total conversation time` : "AI messages per conversation"} icon={BarChart3}/><Metric label={tab === "calls" ? "Call count" : "Chat count"} value={String(tab === "calls" ? filteredCalls.length : filteredChats.length)} detail={agentId === "all" ? `All accessible ${tab === "calls" ? "voice" : "chat"} agents` : "Selected agent"} icon={tab === "calls" ? Phone : MessageSquareText}/></div>
    <div className="grid gap-4 xl:grid-cols-[2fr_1fr]"><Chart id="volume" title={`${tab === "calls" ? "Call" : "Chat"} volume`} focused={focused} setFocused={setFocused}><ResponsiveContainer width="100%" height="100%"><AreaChart data={timeline}><CartesianGrid vertical={false} stroke="#dfe5ec"/><XAxis dataKey="day" tick={{ fontSize: 11 }}/><YAxis allowDecimals={false} tick={{ fontSize: 11 }}/><Tooltip/><Area type="monotone" dataKey={tab} stroke="#4f7df3" strokeWidth={2} fill="#4f7df333"/></AreaChart></ResponsiveContainer></Chart><Chart id="usage" title={tab === "calls" ? "Concurrency used" : "Total AI messages"} focused={focused} setFocused={setFocused}><div className="grid h-full place-items-center text-center"><div><p className="text-5xl font-semibold text-[#253246]">{tab === "calls" ? concurrency : filteredChats.reduce((s, r) => s + r.messages, 0)}</p><p className="mt-2 text-sm text-[#71817c]">{tab === "calls" ? "Peak overlapping calls" : "Across filtered conversations"}</p></div></div></Chart></div>
    {tab === "calls" ? <CallCharts calls={filteredCalls} timeline={timeline} successful={successfulCalls.length} pickup={pickup.length} transferred={transferred.length} voicemail={voicemail.length} focused={focused} setFocused={setFocused}/> : <ChatCharts chats={filteredChats} timeline={timeline} successful={successfulChats.length} focused={focused} setFocused={setFocused}/>}
    <p className="text-center text-xs text-[#84928d]">Select a chart to focus it. Switching model or agent immediately recalculates every statistic from authorized synchronized sessions.</p>
  </div>;
}

function CallCharts({ calls, timeline, successful, pickup, transferred, voicemail, focused, setFocused }: { calls: DashboardDataset["calls"]; timeline: Array<Record<string, string | number>>; successful: number; pickup: number; transferred: number; voicemail: number; focused: string | null; setFocused: (id: string | null) => void }) { return <><div className="grid gap-4 lg:grid-cols-2 xl:grid-cols-4"><Donut id="success" title="Call successful" data={[{ name: "Successful", value: successful }, { name: "Other", value: Math.max(0, calls.length - successful) }]} focused={focused} setFocused={setFocused}/><Donut id="reason" title="Disconnection reason" data={group(calls, (r) => r.endReason ?? r.outcome ?? "Unknown")} focused={focused} setFocused={setFocused}/><Donut id="sentiment" title="User sentiment" data={group(calls, (r) => r.sentiment ?? "Not analyzed")} focused={focused} setFocused={setFocused}/><Donut id="direction" title="Phone inbound/outbound" data={group(calls, (r) => r.channel ?? "Unknown")} focused={focused} setFocused={setFocused}/></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3"><Rate id="pickup" label="Call pickup rate" value={percent(pickup, calls.length)} detail={`${pickup} of ${calls.length} calls`} focused={focused} setFocused={setFocused}/><Rate id="success-rate" label="Call successful rate" value={percent(successful, calls.length)} detail={`${successful} successful outcomes`} focused={focused} setFocused={setFocused}/><Rate id="transfer" label="Call transfer rate" value={percent(transferred, calls.length)} detail={`${transferred} transferred calls`} focused={focused} setFocused={setFocused}/><Rate id="voicemail" label="Voicemail rate" value={percent(voicemail, calls.length)} detail={`${voicemail} voicemail outcomes`} focused={focused} setFocused={setFocused}/><Chart id="duration" title="Average call duration" focused={focused} setFocused={setFocused}><ResponsiveContainer width="100%" height="100%"><LineChart data={timeline}><CartesianGrid vertical={false} stroke="#dfe5ec"/><XAxis dataKey="day" tick={{ fontSize: 10 }}/><YAxis tick={{ fontSize: 10 }}/><Tooltip/><Line type="monotone" dataKey="avgDuration" stroke="#4f7df3" strokeWidth={2}/></LineChart></ResponsiveContainer></Chart><Status title="Call status" data={group(calls, (r) => r.status ?? "Unknown")} focused={focused} setFocused={setFocused}/></div></>; }
function ChatCharts({ chats, timeline, successful, focused, setFocused }: { chats: DashboardDataset["chats"]; timeline: Array<Record<string, string | number>>; successful: number; focused: string | null; setFocused: (id: string | null) => void }) { return <><div className="grid gap-4 lg:grid-cols-3"><Donut id="chat-outcomes" title="Chat outcomes" data={group(chats, (r) => r.outcome ?? "Not analyzed")} focused={focused} setFocused={setFocused}/><Donut id="chat-sentiment" title="User sentiment" data={group(chats, (r) => r.sentiment ?? "Not analyzed")} focused={focused} setFocused={setFocused}/><Status title="Chat status" data={group(chats, (r) => r.status ?? "Unknown")} focused={focused} setFocused={setFocused}/></div><div className="grid gap-4 md:grid-cols-2"><Rate id="chat-success" label="Chat successful rate" value={percent(successful, chats.length)} detail={`${successful} successful chats`} focused={focused} setFocused={setFocused}/><Chart id="chat-timeline" title="Chat volume over time" focused={focused} setFocused={setFocused}><ResponsiveContainer width="100%" height="100%"><BarChart data={timeline}><CartesianGrid vertical={false} stroke="#dfe5ec"/><XAxis dataKey="day" tick={{ fontSize: 10 }}/><YAxis allowDecimals={false}/><Tooltip/><Bar dataKey="chats" fill="#1f7659" radius={[6, 6, 0, 0]}/></BarChart></ResponsiveContainer></Chart></div></>; }
function group<T>(rows: T[], key: (row: T) => string): Datum[] { const values = new Map<string, number>(); for (const row of rows) { const label = key(row); values.set(label, (values.get(label) ?? 0) + 1); } return [...values].map(([name, value]) => ({ name, value })); }
function formatDuration(value: number) { return `${Math.floor(value / 60)}m ${value % 60}s`; }
function Tab({ active, onClick, icon: Icon, children }: { active: boolean; onClick: () => void; icon: typeof Phone; children: React.ReactNode }) { return <button type="button" onClick={onClick} aria-pressed={active} className={`flex items-center gap-2 border-b-2 px-4 py-3 text-sm font-semibold transition ${active ? "border-[#253246] text-[#253246]" : "border-transparent text-[#84928d] hover:text-[#253246]"}`}><Icon className="size-4"/>{children}</button>; }
function Metric({ label, value, detail, icon: Icon }: { label: string; value: string; detail: string; icon: typeof Activity }) { return <article className="glass rounded-2xl p-5"><div className="flex items-center justify-between"><p className="text-sm font-semibold">{label}</p><Icon className="size-4 text-[#4f7df3]"/></div><div className="mt-4 rounded-xl bg-[#f6f7f9] p-5 text-center"><p className="text-3xl font-semibold">{value}</p><p className="mt-2 text-xs text-[#84928d]">{detail}</p></div></article>; }
function Chart({ id, title, focused, setFocused, children }: { id: string; title: string; focused: string | null; setFocused: (id: string | null) => void; children: React.ReactNode }) { const active = focused === id; return <button type="button" onClick={() => setFocused(active ? null : id)} aria-pressed={active} className={`glass min-h-72 rounded-2xl p-5 text-left transition ${active ? "-translate-y-1 border-[#4f7df3] ring-4 ring-[#4f7df320] shadow-2xl" : "hover:-translate-y-0.5 hover:shadow-xl"}`}><p className="mb-4 text-sm font-semibold">{title}</p><div className="h-56">{children}</div></button>; }
function Donut({ id, title, data, focused, setFocused }: { id: string; title: string; data: Datum[]; focused: string | null; setFocused: (id: string | null) => void }) { const total = data.reduce((sum, r) => sum + r.value, 0); return <Chart id={id} title={title} focused={focused} setFocused={setFocused}>{total ? <ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={data} dataKey="value" nameKey="name" innerRadius="52%" outerRadius="76%" paddingAngle={2}>{data.map((r, i) => <Cell key={r.name} fill={COLORS[i % COLORS.length]}/>)}</Pie><Tooltip/><Legend iconSize={8} wrapperStyle={{ fontSize: 10 }}/></PieChart></ResponsiveContainer> : <Empty/>}</Chart>; }
function Rate({ id, label, value, detail, focused, setFocused }: { id: string; label: string; value: string; detail: string; focused: string | null; setFocused: (id: string | null) => void }) { return <Chart id={id} title={label} focused={focused} setFocused={setFocused}><div className="grid h-full place-items-center text-center"><div><p className="text-5xl font-semibold text-[#4f7df3]">{value}</p><p className="mt-3 text-xs text-[#84928d]">{detail}</p></div></div></Chart>; }
function Status({ title, data, focused, setFocused }: { title: string; data: Datum[]; focused: string | null; setFocused: (id: string | null) => void }) { return <Chart id={`status-${title}`} title={title} focused={focused} setFocused={setFocused}>{data.length ? <ResponsiveContainer width="100%" height="100%"><BarChart data={data} layout="vertical"><CartesianGrid horizontal={false} stroke="#dfe5ec"/><XAxis type="number" allowDecimals={false}/><YAxis type="category" dataKey="name" width={90} tick={{ fontSize: 10 }}/><Tooltip/><Bar dataKey="value" fill="#4f7df3" radius={[0, 6, 6, 0]}/></BarChart></ResponsiveContainer> : <Empty/>}</Chart>; }
function Empty() { return <div className="grid h-full place-items-center text-sm text-[#84928d]">No synchronized data</div>; }
