"use client";

import { useMemo, useState } from "react";
import { Bot, Download, MoreVertical, Phone, Search, Settings2 } from "lucide-react";
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import type { DashboardDataset } from "./dashboard-shell";

const control = "h-11 rounded-xl border border-[#d9dee7] bg-white px-3 text-sm outline-none focus:border-[#1f7659] focus:ring-4 focus:ring-[#1f765915]";

export function RetellAgentsView({ agents }: { agents: DashboardDataset["agents"] }) {
  const [search, setSearch] = useState(""); const [selected, setSelected] = useState<string | null>(null);
  const rows = agents.filter((agent) => agent.name.toLowerCase().includes(search.toLowerCase()));
  return <div className="glass overflow-hidden rounded-2xl"><div className="flex flex-col gap-3 border-b p-5 sm:flex-row sm:items-center"><h2 className="font-semibold">Agents</h2><label className="relative sm:ml-auto"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-[#84928d]"/><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search agents" className={`${control} pl-10`}/></label></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left"><thead><tr className="bg-[#f0f3f7] text-xs text-[#596a7a]"><th className="p-4">Agent Name</th><th className="p-4">Agent Type</th><th className="p-4">Channel</th><th className="p-4">Sessions</th><th className="p-4">Status</th><th className="p-4">Last synchronized</th><th/></tr></thead><tbody>{rows.map((agent) => <tr key={agent.id} className="border-b last:border-0"><td className="p-4"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-[#f1f3f8]"><Bot className="size-5 text-[#1f7659]"/></span><span className="font-semibold">{agent.name}</span></div></td><td className="p-4"><span className="rounded-full bg-[#f1f3f8] px-3 py-1 text-xs font-semibold">Managed agent</span></td><td className="p-4 capitalize">{agent.kind}</td><td className="p-4">{agent.kind === "voice" ? agent.calls : agent.chats}</td><td className="p-4 capitalize">{agent.status}</td><td className="p-4 text-sm text-[#71817c]">{agent.modifiedAt ? new Date(agent.modifiedAt).toLocaleString() : "Provider synchronized"}</td><td className="p-4"><button onClick={() => setSelected(selected === agent.id ? null : agent.id)} aria-label="Agent details"><MoreVertical className="size-5"/></button></td></tr>)} </tbody></table>{!rows.length && <Empty>No agents match the current search.</Empty>}</div>{selected && <div className="border-t bg-[#f7f9f8] p-5 text-sm"><b>{agents.find((agent) => agent.id === selected)?.name}</b><p className="mt-1 text-[#71817c]">Retell configuration remains managed by Daiichi. Client users receive reporting access only.</p></div>}</div>;
}

export function RetellPhoneNumbersView({ phoneNumbers, agents }: { phoneNumbers: NonNullable<DashboardDataset["phoneNumbers"]>; agents: DashboardDataset["agents"] }) {
  const [search, setSearch] = useState(""); const [selected, setSelected] = useState<string | null>(null);
  const rows = phoneNumbers.filter((number) => `${number.prettyNumber} ${number.nickname}`.toLowerCase().includes(search.toLowerCase()));
  const chosen = rows.find((number) => number.number === selected);
  return <div className="glass min-h-[540px] overflow-hidden rounded-2xl md:grid md:grid-cols-[330px_1fr]"><aside className="border-r p-5"><div className="flex items-center justify-between"><h2 className="flex items-center gap-2 font-semibold"><Phone className="size-4"/>Phone Numbers</h2></div><label className="relative mt-5 block"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-[#84928d]"/><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search phone numbers" className={`${control} w-full pl-10`}/></label><div className="mt-4 space-y-2">{rows.map((number) => <button key={number.number} onClick={() => setSelected(number.number)} className="w-full rounded-xl border bg-white p-4 text-left hover:border-[#1f7659]"><p className="font-semibold">{number.prettyNumber}</p><p className="text-xs text-[#71817c]">{number.nickname}</p></button>)}</div></aside><section className="grid place-items-center p-8">{chosen ? <div className="w-full max-w-2xl"><p className="text-xs font-bold uppercase tracking-wider text-[#1f7659]">{chosen.type}</p><h3 className="mt-2 text-3xl font-semibold">{chosen.prettyNumber}</h3><p className="mt-2 text-[#71817c]">{chosen.nickname}</p><div className="mt-6 grid gap-4 sm:grid-cols-2"><Binding title="Inbound agents" ids={chosen.inboundAgentIds} agents={agents}/><Binding title="Outbound agents" ids={chosen.outboundAgentIds} agents={agents}/></div></div> : <Empty>{rows.length ? "Select a phone number to view its Retell bindings." : "You don't have any phone numbers."}</Empty>}</section></div>;
}

function Binding({ title, ids, agents }: { title: string; ids: string[]; agents: DashboardDataset["agents"] }) { return <div className="rounded-2xl bg-[#f3f6f4] p-5"><p className="text-sm font-semibold">{title}</p><div className="mt-3 space-y-2">{ids.map((id) => <p key={id} className="text-sm">{agents.find((agent) => agent.providerId === id)?.name ?? "Agent outside current access"}</p>)}{!ids.length && <p className="text-sm text-[#84928d]">No binding</p>}</div></div>; }

export function SessionHistoryView({ kind, calls, chats }: { kind: "call" | "chat"; calls: DashboardDataset["calls"]; chats: DashboardDataset["chats"] }) {
  const [search, setSearch] = useState(""); const [status, setStatus] = useState("all"); const [columnsOpen, setColumnsOpen] = useState(false);
  const [visible, setVisible] = useState<Record<string, boolean>>({ duration: true, channel: true, cost: true, session: true, reason: true, status: true, sentiment: true });
  const sessions = kind === "call" ? calls.map((call) => ({ id: call.sessionId ?? `${call.agent}-${call.time}`, time: call.time, agent: call.agent, duration: call.duration, channel: call.channel ?? "phone_call", cost: call.cost ?? "—", reason: call.endReason ?? call.outcome, status: call.status ?? "ended", sentiment: call.sentiment ?? "Neutral" })) : chats.map((chat) => ({ id: chat.sessionId ?? chat.id, time: chat.time, agent: chat.agent, duration: `${chat.messages} messages`, channel: "api_chat", cost: chat.cost ?? "—", reason: chat.outcome, status: chat.status, sentiment: chat.sentiment ?? "Neutral" }));
  const rows = sessions.filter((row) => (status === "all" || row.status === status) && `${row.id} ${row.agent} ${row.reason}`.toLowerCase().includes(search.toLowerCase()));
  const exportRows = () => downloadCsv(`${kind}-history.csv`, rows);
  return <div className="glass min-h-[520px] overflow-hidden rounded-2xl"><div className="flex flex-wrap items-center gap-3 p-5"><h2 className="mr-auto font-semibold">{kind === "call" ? "Call" : "Chat"} History</h2><label className="relative"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-[#84928d]"/><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search sessions" className={`${control} pl-10`}/></label><select value={status} onChange={(e) => setStatus(e.target.value)} className={control}><option value="all">All statuses</option><option value="ended">Ended</option><option value="ongoing">Ongoing</option><option value="error">Error</option></select><div className="relative"><button onClick={() => setColumnsOpen(!columnsOpen)} className={`${control} flex items-center gap-2`}><Settings2 className="size-4"/>Columns</button>{columnsOpen && <div className="absolute right-0 top-12 z-20 w-48 rounded-xl border bg-white p-3 shadow-xl">{Object.keys(visible).map((column) => <label key={column} className="flex gap-2 p-2 text-sm capitalize"><input type="checkbox" checked={visible[column]} onChange={() => setVisible((current) => ({ ...current, [column]: !current[column] }))}/>{column}</label>)}</div>}</div><button onClick={exportRows} className={`${control} flex items-center gap-2 bg-[#253246] text-white`}><Download className="size-4"/>Export</button></div><div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-left"><thead><tr className="bg-[#f1f3f5] text-xs text-[#596a7a]"><th className="p-4">Time</th><th className="p-4">Agent</th>{visible.duration&&<th className="p-4">Duration</th>}{visible.channel&&<th className="p-4">Channel Type</th>}{visible.cost&&<th className="p-4">Cost</th>}{visible.session&&<th className="p-4">Session ID</th>}{visible.reason&&<th className="p-4">End Reason</th>}{visible.status&&<th className="p-4">Session Status</th>}{visible.sentiment&&<th className="p-4">User Sentiment</th>}</tr></thead><tbody>{rows.map((row) => <tr key={row.id} className="border-b text-sm"><td className="p-4">{row.time}</td><td className="p-4">{row.agent}</td>{visible.duration&&<td className="p-4">{row.duration}</td>}{visible.channel&&<td className="p-4">{row.channel}</td>}{visible.cost&&<td className="p-4">{row.cost}</td>}{visible.session&&<td className="max-w-52 truncate p-4" title={row.id}>{row.id}</td>}{visible.reason&&<td className="p-4">{row.reason}</td>}{visible.status&&<td className="p-4 capitalize">{row.status}</td>}{visible.sentiment&&<td className="p-4">{row.sentiment}</td>}</tr>)}</tbody></table>{!rows.length&&<Empty>No sessions match the current filters.</Empty>}</div></div>;
}

export function RetellContactsView({ calls }: { calls: DashboardDataset["calls"] }) {
  const [search, setSearch] = useState(""); const [agent, setAgent] = useState("all");
  const contacts = useMemo(() => Array.from(new Map(calls.map((call) => [call.number, call])).values()), [calls]);
  const rows = contacts.filter((contact) => (agent === "all" || contact.agent === agent) && `${contact.contact} ${contact.number}`.toLowerCase().includes(search.toLowerCase()));
  const agents = Array.from(new Set(calls.map((call) => call.agent)));
  return <div className="glass min-h-[520px] overflow-hidden rounded-2xl"><div className="flex flex-wrap items-center gap-3 p-5"><h2 className="mr-auto font-semibold">Contacts</h2><select value={agent} onChange={(e) => setAgent(e.target.value)} className={control}><option value="all">All agents</option>{agents.map((name) => <option key={name}>{name}</option>)}</select><label className="relative"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-[#84928d]"/><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search" className={`${control} pl-10`}/></label><button onClick={() => downloadCsv("contacts.csv", rows)} className={`${control} flex items-center gap-2 bg-[#253246] text-white`}><Download className="size-4"/>Export</button></div><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left"><thead><tr className="bg-[#f1f3f5] text-xs text-[#596a7a]"><th className="p-4">Phone Number</th><th className="p-4">Contact Name</th><th className="p-4">Related Agent</th><th className="p-4">Latest Conversation</th><th className="p-4">Do Not Call</th><th className="p-4">External ID</th></tr></thead><tbody>{rows.map((contact) => <tr key={contact.number} className="border-b text-sm"><td className="p-4">{contact.number}</td><td className="p-4">{contact.contact}</td><td className="p-4">{contact.agent}</td><td className="p-4">{contact.time}</td><td className="p-4">Not recorded</td><td className="p-4 text-[#84928d]">—</td></tr>)}</tbody></table>{!rows.length&&<Empty>No authorized contacts match the filters.</Empty>}</div></div>;
}

export function RetellAnalyticsView({ calls, chats, agents }: { calls: DashboardDataset["calls"]; chats: DashboardDataset["chats"]; agents: DashboardDataset["agents"] }) {
  const [tab, setTab] = useState<"calls"|"chats">("calls"); const [agent, setAgent] = useState("all");
  const filteredCalls = calls.filter((row) => agent === "all" || row.agentId === agent); const filteredChats = chats.filter((row) => agent === "all" || row.agentId === agent);
  const rows = tab === "calls" ? filteredCalls : filteredChats; const breakdown = agents.map((item) => ({ name: item.name.length > 18 ? `${item.name.slice(0,18)}…` : item.name, sessions: tab === "calls" ? filteredCalls.filter((row) => row.agentId === item.id).length : filteredChats.filter((row) => row.agentId === item.id).length }));
  const success = rows.filter((row) => /success|book|resolved|qualified/i.test(row.outcome)).length;
  return <div className="space-y-5"><div className="glass rounded-2xl p-5"><div className="flex flex-wrap items-center gap-3"><button onClick={() => setTab("calls")} className={`border-b-2 px-3 py-2 font-semibold ${tab==="calls"?"border-[#253246]":"border-transparent text-[#84928d]"}`}>Call Dashboard</button><button onClick={() => setTab("chats")} className={`border-b-2 px-3 py-2 font-semibold ${tab==="chats"?"border-[#253246]":"border-transparent text-[#84928d]"}`}>Chat Dashboard</button><select value={agent} onChange={(e) => setAgent(e.target.value)} className={`${control} ml-auto`}><option value="all">All agents</option>{agents.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></div></div><div className="grid gap-4 sm:grid-cols-3"><Metric label="Total sessions" value={String(rows.length)}/><Metric label="Successful outcomes" value={String(success)}/><Metric label="Success rate" value={`${rows.length ? Math.round(success/rows.length*100) : 0}%`}/></div><div className="glass rounded-2xl p-6"><h3 className="font-semibold">Sessions by agent</h3><div className="mt-5 h-72"><ResponsiveContainer width="100%" height="100%"><BarChart data={breakdown}><CartesianGrid vertical={false} stroke="#173f3312"/><XAxis dataKey="name" tick={{fontSize:11}}/><YAxis allowDecimals={false}/><Tooltip/><Bar dataKey="sessions" fill="#1f7659" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></div></div></div>;
}

function Metric({ label, value }: { label: string; value: string }) { return <article className="glass rounded-2xl p-6"><p className="text-sm text-[#71817c]">{label}</p><p className="mt-2 text-3xl font-semibold">{value}</p></article>; }
function Empty({ children }: { children: React.ReactNode }) { return <div className="p-12 text-center text-sm text-[#84928d]">{children}</div>; }
function downloadCsv(filename: string, rows: unknown[]) { const records = rows as Record<string, unknown>[]; const first = records[0]; if (!first) return; const keys = Object.keys(first); const csv = [keys.join(","), ...records.map((row) => keys.map((key) => JSON.stringify(row[key] ?? "")).join(","))].join("\n"); const url = URL.createObjectURL(new Blob([csv], { type: "text/csv" })); const link = document.createElement("a"); link.href=url; link.download=filename; link.click(); URL.revokeObjectURL(url); }
