"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { Check, ChevronDown, ChevronLeft, ChevronRight, CirclePlus, Filter, MinusCircle, RefreshCw, Settings2 } from "lucide-react";
import type { DashboardDataset } from "./dashboard-shell";

type Kind = "call" | "chat";
type OpenPanel = "filters" | "columns" | "actions" | null;
type Row = { id: string; time: string; agent: string; transferAgent: string; batchId: string; duration: string; channel: string; reason: string; status: string; sentiment: string; successful: boolean; from: string; to: string };
type ExtraValues = { transferAgent: string; batchId: string; channel: string; minimumDuration: string; from: string; to: string; reason: string; successful: string };

const control = "h-11 rounded-xl border border-[#d7deea] bg-white px-3 text-sm text-[#253246] shadow-sm outline-none transition hover:border-[#aeb8c8] focus:border-[#4f647e] focus:ring-4 focus:ring-[#4f647e12]";
const initialExtras: ExtraValues = { transferAgent: "", batchId: "", channel: "all", minimumDuration: "", from: "", to: "", reason: "all", successful: "all" };
const coreFields = new Set(["Agent", "Call ID", "Chat ID", "User Sentiment", "Call Status", "Chat Status"]);
const extraKey: Record<string, keyof ExtraValues> = { "Transfer Agent": "transferAgent", "Batch Call ID": "batchId", Type: "channel", Duration: "minimumDuration", From: "from", To: "to", "Disconnection Reason": "reason", "Call Successful": "successful", "Chat Successful": "successful" };

export function SessionHistoryView({ kind, calls, chats }: { kind: Kind; calls: DashboardDataset["calls"]; chats: DashboardDataset["chats"] }) {
  const rootRef = useRef<HTMLDivElement>(null);
  const [openPanel, setOpenPanel] = useState<OpenPanel>(null);
  const [filterTab, setFilterTab] = useState("Base");
  const [agent, setAgent] = useState("all");
  const [status, setStatus] = useState("all");
  const [sentiment, setSentiment] = useState("all");
  const [sessionQuery, setSessionQuery] = useState("");
  const [enabledExtras, setEnabledExtras] = useState<Array<keyof ExtraValues>>([]);
  const [extras, setExtras] = useState<ExtraValues>(initialExtras);
  const [page, setPage] = useState(1);
  const [pageSize, setPageSize] = useState(50);
  const [visible, setVisible] = useState<Record<string, boolean>>({ agent: true, duration: kind === "call", channel: kind === "call", session: true, reason: kind === "call", status: true, sentiment: true, from: kind === "chat", to: kind === "chat" });

  useEffect(() => {
    const dismiss = (event: PointerEvent) => { if (rootRef.current && !rootRef.current.contains(event.target as Node)) setOpenPanel(null); };
    const escape = (event: KeyboardEvent) => { if (event.key === "Escape") setOpenPanel(null); };
    document.addEventListener("pointerdown", dismiss); window.addEventListener("keydown", escape);
    return () => { document.removeEventListener("pointerdown", dismiss); window.removeEventListener("keydown", escape); };
  }, []);

  const sessions: Row[] = useMemo(() => kind === "call" ? calls.map((call) => ({ id: call.sessionId ?? `${call.agent}-${call.time}`, time: call.time, agent: call.agent, transferAgent: /transfer/i.test(`${call.endReason} ${call.outcome}`) ? "Transferred" : "", batchId: "", duration: call.duration, channel: call.channel ?? "phone_call", reason: call.endReason ?? call.outcome, status: call.status ?? "ended", sentiment: call.sentiment ?? "Not analyzed", successful: /success|book|resolved|qualified|completed/i.test(call.outcome), from: call.number, to: "—" })) : chats.map((chat) => ({ id: chat.sessionId ?? chat.id, time: chat.time, agent: chat.agent, transferAgent: "", batchId: "", duration: `${chat.messages} messages`, channel: "api_chat", reason: chat.outcome, status: chat.status, sentiment: chat.sentiment ?? "Not analyzed", successful: /success|book|resolved|qualified|completed/i.test(chat.outcome), from: "—", to: "—" })), [calls, chats, kind]);
  const agents = unique(sessions.map((row) => row.agent));
  const statuses = unique(sessions.map((row) => row.status));
  const sentiments = unique(sessions.map((row) => row.sentiment));
  const channels = unique(sessions.map((row) => row.channel));
  const reasons = unique(sessions.map((row) => row.reason));
  const rows = sessions.filter((row) => (agent === "all" || row.agent === agent) && (status === "all" || row.status === status) && (sentiment === "all" || row.sentiment === sentiment) && row.id.toLowerCase().includes(sessionQuery.toLowerCase()) && matchesExtras(row, enabledExtras, extras));
  const totalPages = Math.max(1, Math.ceil(rows.length / pageSize));
  const safePage = Math.min(page, totalPages);
  const shownRows = rows.slice((safePage - 1) * pageSize, safePage * pageSize);
  const activeFilters = Number(agent !== "all") + Number(status !== "all") + Number(sentiment !== "all") + Number(Boolean(sessionQuery)) + enabledExtras.filter((key) => extraHasValue(key, extras[key])).length;
  const tabs = kind === "call" ? ["Base", "Post Call Analysis", "Metadata", "Dynamic Variables"] : ["Base", "Post Chat Analysis"];
  const fields = kind === "call" ? ["Agent", "Transfer Agent", "Call ID", "Batch Call ID", "Type", "Duration", "From", "To", "User Sentiment", "Disconnection Reason", "Call Status", "Call Successful"] : ["Agent", "Chat ID", "User Sentiment", "Disconnection Reason", "Chat Successful", "Chat Status"];

  function toggle(panel: Exclude<OpenPanel, null>) { setOpenPanel((current) => current === panel ? null : panel); }
  function toggleExtra(field: string) { const key = extraKey[field]; if (!key) return; setEnabledExtras((current) => current.includes(key) ? current.filter((item) => item !== key) : [...current, key]); setPage(1); }
  function setExtra(key: keyof ExtraValues, value: string) { setExtras((current) => ({ ...current, [key]: value })); setPage(1); }
  function clearFilters() { setAgent("all"); setStatus("all"); setSentiment("all"); setSessionQuery(""); setEnabledExtras([]); setExtras(initialExtras); setPage(1); }
  function exportRows() { downloadCsv(`${kind}-history.csv`, rows); setOpenPanel(null); }

  return <div ref={rootRef} className="glass relative min-h-[520px] rounded-2xl">
    <header className="rounded-t-2xl border-b border-[#dce2e8] bg-white/90 p-4"><h2 className="flex items-center gap-2 font-semibold"><RefreshCw className="size-4 text-[#667487]"/>{kind === "call" ? "Call" : "Chat"} History</h2><div className="mt-4 flex flex-wrap items-center gap-3">
      <div className="relative"><button type="button" aria-expanded={openPanel === "filters"} onClick={() => toggle("filters")} className={`${control} flex items-center gap-2 px-4 ${openPanel === "filters" ? "border-[#4f647e] ring-4 ring-[#4f647e12]" : ""}`}><Filter className="size-4"/>Filter{activeFilters > 0 && <span className="grid size-5 place-items-center rounded-full bg-[#2d394b] text-[10px] font-bold text-white">{activeFilters}</span>}</button>
        {openPanel === "filters" && <Panel className="left-0 w-[min(92vw,540px)]"><div className="flex gap-5 overflow-x-auto border-b px-4 pt-4">{tabs.map((tab) => <button type="button" key={tab} onClick={() => setFilterTab(tab)} className={`whitespace-nowrap border-b-2 pb-3 text-sm ${filterTab === tab ? "border-[#253246] font-semibold" : "border-transparent text-[#697789]"}`}>{tab}</button>)}</div>{filterTab === "Base" ? <div className="max-h-[480px] overflow-y-auto p-4"><div className="grid gap-3 sm:grid-cols-2"><FilterSelect label="Agent" value={agent} setValue={(value) => { setAgent(value); setPage(1); }} values={agents}/><FilterSelect label={`${kind === "call" ? "Call" : "Chat"} Status`} value={status} setValue={(value) => { setStatus(value); setPage(1); }} values={statuses}/><FilterSelect label="User Sentiment" value={sentiment} setValue={(value) => { setSentiment(value); setPage(1); }} values={sentiments}/><TextFilter label={`${kind === "call" ? "Call" : "Chat"} ID`} value={sessionQuery} setValue={(value) => { setSessionQuery(value); setPage(1); }} placeholder="Search exact or partial ID"/></div>
          {enabledExtras.length > 0 && <div className="mt-4 grid gap-3 rounded-xl bg-[#f5f7f9] p-3 sm:grid-cols-2">{enabledExtras.map((key) => <ExtraFilter key={key} filterKey={key} value={extras[key]} setValue={(value) => setExtra(key, value)} channels={channels} reasons={reasons}/>)}</div>}
          <div className="mt-5 border-t pt-4"><p className="mb-2 text-[11px] font-bold uppercase tracking-wider text-[#84928d]">Available fields</p><div className="grid gap-1 sm:grid-cols-2">{fields.map((field) => { const key = extraKey[field]; const active = coreFields.has(field) || Boolean(key && enabledExtras.includes(key)); return <button type="button" key={field} disabled={coreFields.has(field)} onClick={() => toggleExtra(field)} className={`flex items-center gap-2 rounded-lg px-2 py-2 text-left text-xs transition ${active ? "bg-[#e9f1ed] font-semibold text-[#1f7659]" : "text-[#596a7a] hover:bg-[#f1f3f5]"}`}>{active ? <MinusCircle className="size-3.5"/> : <CirclePlus className="size-3.5"/>}{field}<span className="ml-auto text-[10px]">{coreFields.has(field) ? "Shown" : active ? "Added" : "Add"}</span></button>; })}</div></div></div> : <div className="grid min-h-56 place-items-center p-8 text-center text-sm text-[#84928d]">No synchronized fields are available for this category.</div>}<footer className="flex items-center justify-between border-t p-4"><button type="button" onClick={clearFilters} disabled={!activeFilters && !enabledExtras.length} className="text-sm font-semibold text-[#667487] disabled:opacity-35">Clear all</button><button type="button" onClick={() => setOpenPanel(null)} className="rounded-xl bg-[#2d394b] px-5 py-2.5 text-sm font-semibold text-white">Apply filters</button></footer></Panel>}
        {openPanel === "filters" && filterTab !== "Base" && filterTab.includes("Analysis") && <PostAnalysisLocator kind={kind} tabs={tabs} activeTab={filterTab} setActiveTab={setFilterTab} agents={agents} selectedAgent={agent} setSelectedAgent={(value) => { setAgent(value); setPage(1); }} sentiments={sentiments} sentiment={sentiment} setSentiment={(value) => { setSentiment(value); setPage(1); }} successful={extras.successful} setSuccessful={(value) => { setEnabledExtras((current) => current.includes("successful") ? current : [...current, "successful"]); setExtra("successful", value); }} clear={clearFilters} apply={() => setOpenPanel(null)}/>}
      </div>
      <div className="relative ml-auto"><button type="button" aria-label="Manage columns" aria-expanded={openPanel === "columns"} onClick={() => toggle("columns")} className={`${control} grid w-11 place-items-center px-0`}><Settings2 className="size-4"/></button>{openPanel === "columns" && <Panel className="right-0 w-56 p-3"><p className="px-2 pb-2 text-[11px] font-bold uppercase tracking-wider text-[#84928d]">Visible columns</p>{Object.keys(visible).filter((column) => kind === "chat" || !["from", "to"].includes(column)).map((column) => <label key={column} className="flex cursor-pointer items-center gap-3 rounded-lg px-2 py-2 text-sm hover:bg-[#f2f4f7]"><input type="checkbox" checked={visible[column]} onChange={() => setVisible((current) => ({ ...current, [column]: !current[column] }))} className="size-4 accent-[#2d394b]"/>{column === "session" ? "Session ID" : title(column)}</label>)}</Panel>}</div>
      <div className="relative"><button type="button" aria-expanded={openPanel === "actions"} onClick={() => toggle("actions")} className="flex h-11 items-center gap-2 rounded-xl bg-[#2d394b] px-4 text-sm font-semibold text-white">Actions<ChevronDown className={`size-4 transition ${openPanel === "actions" ? "rotate-180" : ""}`}/></button>{openPanel === "actions" && <Panel className="right-0 w-56 p-2"><button type="button" onClick={exportRows} disabled={!rows.length} className="flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-left text-sm hover:bg-[#f2f4f7] disabled:opacity-40"><Check className="size-4"/>Export current view</button></Panel>}</div>
    </div></header>
    <div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-left"><thead><tr className="bg-[#f1f3f5] text-xs text-[#596a7a]"><th className="p-4">Time</th>{visible.agent&&<th className="p-4">Agent</th>}{visible.duration&&<th className="p-4">Duration</th>}{visible.channel&&<th className="p-4">Channel Type</th>}{visible.session&&<th className="p-4">Session ID</th>}{visible.reason&&<th className="p-4">End Reason</th>}{visible.status&&<th className="p-4">Session Status</th>}{visible.sentiment&&<th className="p-4">User Sentiment</th>}{visible.from&&<th className="p-4">From</th>}{visible.to&&<th className="p-4">To</th>}</tr></thead><tbody>{shownRows.map((row) => <tr key={row.id} className="border-b border-[#dfe4e8] text-sm hover:bg-[#f7f9fb]"><td className="whitespace-nowrap p-4">{row.time}</td>{visible.agent&&<td className="p-4">{row.agent}</td>}{visible.duration&&<td className="p-4">{row.duration}</td>}{visible.channel&&<td className="p-4">{row.channel}</td>}{visible.session&&<td className="max-w-56 truncate p-4" title={row.id}>{row.id}</td>}{visible.reason&&<td className="p-4">{row.reason}</td>}{visible.status&&<td className="p-4 capitalize">{row.status}</td>}{visible.sentiment&&<td className="p-4">{row.sentiment}</td>}{visible.from&&<td className="p-4">{row.from}</td>}{visible.to&&<td className="p-4">{row.to}</td>}</tr>)}</tbody></table>{!shownRows.length && <div className="grid min-h-48 place-items-center border-b text-sm text-[#84928d]">No sessions match the current filters.</div>}</div>
    <footer className="flex flex-col gap-3 rounded-b-2xl bg-white/80 p-4 text-sm text-[#71817c] sm:flex-row sm:items-center"><span>Page {safePage} of {totalPages} · Total Sessions: {rows.length}</span><div className="flex items-center gap-2 sm:ml-auto"><button type="button" aria-label="Previous page" disabled={safePage <= 1} onClick={() => setPage((current) => Math.max(1, current - 1))} className="grid size-9 place-items-center rounded-lg border bg-white disabled:opacity-30"><ChevronLeft className="size-4"/></button><span className="grid size-9 place-items-center rounded-lg bg-[#f1f3f7] font-semibold text-[#253246]">{safePage}</span><button type="button" aria-label="Next page" disabled={safePage >= totalPages} onClick={() => setPage((current) => Math.min(totalPages, current + 1))} className="grid size-9 place-items-center rounded-lg border bg-white disabled:opacity-30"><ChevronRight className="size-4"/></button><select value={pageSize} onChange={(event) => { setPageSize(Number(event.target.value)); setPage(1); }} aria-label="Rows per page" className="ml-2 h-9 rounded-lg border bg-white px-3"><option value={25}>25 / page</option><option value={50}>50 / page</option><option value={100}>100 / page</option></select></div></footer>
  </div>;
}

function PostAnalysisLocator({ kind, tabs, activeTab, setActiveTab, agents, selectedAgent, setSelectedAgent, sentiments, sentiment, setSentiment, successful, setSuccessful, clear, apply }: { kind: Kind; tabs: string[]; activeTab: string; setActiveTab: (tab: string) => void; agents: string[]; selectedAgent: string; setSelectedAgent: (agent: string) => void; sentiments: string[]; sentiment: string; setSentiment: (value: string) => void; successful: string; setSuccessful: (value: string) => void; clear: () => void; apply: () => void }) {
  const [pickerOpen, setPickerOpen] = useState(false);
  const [search, setSearch] = useState("");
  const matchingAgents = agents.filter((name) => name.toLowerCase().includes(search.toLowerCase()));
  return <div className="absolute left-0 top-[calc(100%+8px)] z-[110] w-[min(92vw,540px)] overflow-visible rounded-2xl border border-[#cad3de] bg-white text-[#253246] shadow-[0_20px_55px_rgba(35,49,67,.22)]">
    <div className="flex gap-5 overflow-x-auto border-b px-4 pt-4">{tabs.map((tab) => <button type="button" key={tab} onClick={() => setActiveTab(tab)} className={`whitespace-nowrap border-b-2 pb-3 text-sm ${activeTab === tab ? "border-[#253246] font-semibold" : "border-transparent text-[#697789]"}`}>{tab}</button>)}</div>
    <div className="min-h-72 p-4"><p className="text-sm font-semibold">Locate field with agent selector</p><div className="relative mt-2"><button type="button" aria-expanded={pickerOpen} onClick={() => setPickerOpen((open) => !open)} className={`${control} flex w-full items-center justify-between text-left`}><span className={selectedAgent === "all" ? "text-[#84928d]" : "truncate"}>{selectedAgent === "all" ? "Select agent" : selectedAgent}</span><ChevronDown className={`size-4 transition ${pickerOpen ? "rotate-180" : ""}`}/></button>{pickerOpen && <div className="absolute left-0 top-12 z-[120] w-full overflow-hidden rounded-2xl border border-[#cad3de] bg-white shadow-2xl"><div className="border-b p-3"><input autoFocus value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search agents..." className={`${control} w-full`}/></div><div className="max-h-56 overflow-y-auto p-2"><button type="button" onClick={() => { setSelectedAgent("all"); setPickerOpen(false); }} className="w-full rounded-xl px-3 py-3 text-left text-sm hover:bg-[#f1f3f5]">All agents</button>{matchingAgents.map((name) => <button type="button" key={name} onClick={() => { setSelectedAgent(name); setPickerOpen(false); }} className={`w-full rounded-xl px-3 py-3 text-left hover:bg-[#f1f3f5] ${selectedAgent === name ? "bg-[#eef3f0]" : ""}`}><span className="block text-sm font-semibold">{name}</span><span className="text-xs text-[#84928d]">Synchronized {kind} agent</span></button>)}{!matchingAgents.length && <p className="p-5 text-center text-sm text-[#84928d]">No agents match this search.</p>}</div></div>}</div>
      <div className="mt-5 grid gap-3 sm:grid-cols-2"><FilterSelect label="User Sentiment" value={sentiment} setValue={setSentiment} values={sentiments}/><FilterSelect label={`${kind === "call" ? "Call" : "Chat"} Successful`} value={successful} setValue={setSuccessful} values={["yes", "no"]}/></div><p className="mt-4 text-xs text-[#84928d]">Only analysis fields returned by Retell are shown. Selecting an agent or field filters the history table immediately.</p>
    </div><footer className="flex items-center justify-between border-t p-4"><button type="button" onClick={clear} className="text-sm font-semibold text-[#667487]">Clear all</button><button type="button" onClick={apply} className="rounded-xl bg-[#2d394b] px-5 py-2.5 text-sm font-semibold text-white">Apply filters</button></footer>
  </div>;
}

function matchesExtras(row: Row, enabled: Array<keyof ExtraValues>, values: ExtraValues) { return enabled.every((key) => { const value = values[key].trim().toLowerCase(); if (!extraHasValue(key, value)) return true; if (key === "channel") return row.channel.toLowerCase() === value; if (key === "reason") return row.reason.toLowerCase() === value; if (key === "successful") return row.successful === (value === "yes"); if (key === "minimumDuration") return durationSeconds(row.duration) >= Number(value); return String(row[key]).toLowerCase().includes(value); }); }
function extraHasValue(key: keyof ExtraValues, value: string) { return key === "channel" || key === "reason" || key === "successful" ? value !== "all" : Boolean(value); }
function durationSeconds(value: string) { const [minutes = 0, seconds = 0] = value.split(":").map(Number); return Number.isFinite(minutes + seconds) ? minutes * 60 + seconds : 0; }
function ExtraFilter({ filterKey, value, setValue, channels, reasons }: { filterKey: keyof ExtraValues; value: string; setValue: (value: string) => void; channels: string[]; reasons: string[] }) { if (filterKey === "channel") return <FilterSelect label="Type" value={value} setValue={setValue} values={channels}/>; if (filterKey === "reason") return <FilterSelect label="Disconnection Reason" value={value} setValue={setValue} values={reasons}/>; if (filterKey === "successful") return <FilterSelect label="Successful" value={value} setValue={setValue} values={["yes", "no"]}/>; const labels: Record<string, string> = { transferAgent: "Transfer Agent", batchId: "Batch Call ID", minimumDuration: "Minimum duration (seconds)", from: "From", to: "To" }; const label = labels[filterKey] ?? "Filter"; return <TextFilter label={label} value={value} setValue={setValue} placeholder={`Filter by ${label.toLowerCase()}`} type={filterKey === "minimumDuration" ? "number" : "text"}/>; }
function Panel({ className, children }: { className: string; children: React.ReactNode }) { return <div className={`absolute top-[calc(100%+8px)] z-[100] overflow-hidden rounded-2xl border border-[#cad3de] bg-white text-[#253246] shadow-[0_20px_55px_rgba(35,49,67,.22)] ${className}`}>{children}</div>; }
function FilterSelect({ label, value, setValue, values }: { label: string; value: string; setValue: (value: string) => void; values: string[] }) { return <label className="text-xs font-semibold text-[#596a7a]">{label}<select value={value} onChange={(event) => setValue(event.target.value)} className={`${control} mt-2 w-full`}><option value="all">All</option>{values.map((item) => <option key={item} value={item}>{item}</option>)}</select></label>; }
function TextFilter({ label, value, setValue, placeholder, type = "text" }: { label: string; value: string; setValue: (value: string) => void; placeholder: string; type?: string }) { return <label className="text-xs font-semibold text-[#596a7a]">{label}<input type={type} min={type === "number" ? 0 : undefined} value={value} onChange={(event) => setValue(event.target.value)} placeholder={placeholder} className={`${control} mt-2 w-full`}/></label>; }
function unique(values: string[]) { return Array.from(new Set(values.filter(Boolean))).sort(); }
function title(value: string) { return value.charAt(0).toUpperCase() + value.slice(1); }
function downloadCsv(filename: string, rows: Row[]) { const first = rows[0]; if (!first) return; const keys = Object.keys(first) as Array<keyof Row>; const csv = [keys.join(","), ...rows.map((row) => keys.map((key) => JSON.stringify(row[key] ?? "")).join(","))].join("\n"); const url = URL.createObjectURL(new Blob([csv], { type: "text/csv" })); const link = document.createElement("a"); link.href = url; link.download = filename; link.click(); URL.revokeObjectURL(url); }
