"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { Check, ChevronDown, ChevronLeft, ChevronRight, CirclePlus, Filter, RefreshCw, Settings2 } from "lucide-react";
import type { DashboardDataset } from "./dashboard-shell";

type Kind = "call" | "chat";
type OpenPanel = "filters" | "columns" | "actions" | null;
type Row = { id: string; time: string; agent: string; duration: string; channel: string; reason: string; status: string; sentiment: string; from: string; to: string };

const control = "h-11 rounded-xl border border-[#d7deea] bg-white px-3 text-sm text-[#253246] shadow-sm outline-none transition hover:border-[#aeb8c8] focus:border-[#4f647e] focus:ring-4 focus:ring-[#4f647e12]";

export function SessionHistoryView({ kind, calls, chats }: { kind: Kind; calls: DashboardDataset["calls"]; chats: DashboardDataset["chats"] }) {
  const rootRef = useRef<HTMLDivElement>(null);
  const [openPanel, setOpenPanel] = useState<OpenPanel>(null);
  const [filterTab, setFilterTab] = useState("Base");
  const [agent, setAgent] = useState("all"); const [status, setStatus] = useState("all"); const [sentiment, setSentiment] = useState("all"); const [sessionQuery, setSessionQuery] = useState("");
  const [page, setPage] = useState(1); const [pageSize, setPageSize] = useState(50);
  const [visible, setVisible] = useState<Record<string, boolean>>({ agent: true, duration: kind === "call", channel: kind === "call", session: true, reason: kind === "call", status: true, sentiment: true, from: kind === "chat", to: kind === "chat" });

  useEffect(() => {
    const dismiss = (event: PointerEvent) => { if (rootRef.current && !rootRef.current.contains(event.target as Node)) setOpenPanel(null); };
    const escape = (event: KeyboardEvent) => { if (event.key === "Escape") setOpenPanel(null); };
    document.addEventListener("pointerdown", dismiss); window.addEventListener("keydown", escape);
    return () => { document.removeEventListener("pointerdown", dismiss); window.removeEventListener("keydown", escape); };
  }, []);

  const sessions: Row[] = useMemo(() => kind === "call" ? calls.map((call) => ({ id: call.sessionId ?? `${call.agent}-${call.time}`, time: call.time, agent: call.agent, duration: call.duration, channel: call.channel ?? "phone_call", reason: call.endReason ?? call.outcome, status: call.status ?? "ended", sentiment: call.sentiment ?? "Neutral", from: call.number, to: "—" })) : chats.map((chat) => ({ id: chat.sessionId ?? chat.id, time: chat.time, agent: chat.agent, duration: `${chat.messages} messages`, channel: "api_chat", reason: chat.outcome, status: chat.status, sentiment: chat.sentiment ?? "Neutral", from: "—", to: "—" })), [calls, chats, kind]);
  const agents = unique(sessions.map((row) => row.agent)); const statuses = unique(sessions.map((row) => row.status)); const sentiments = unique(sessions.map((row) => row.sentiment));
  const rows = sessions.filter((row) => (agent === "all" || row.agent === agent) && (status === "all" || row.status === status) && (sentiment === "all" || row.sentiment === sentiment) && `${row.id} ${row.reason}`.toLowerCase().includes(sessionQuery.toLowerCase()));
  const totalPages = Math.max(1, Math.ceil(rows.length / pageSize)); const safePage = Math.min(page, totalPages); const shownRows = rows.slice((safePage - 1) * pageSize, safePage * pageSize);
  const activeFilters = Number(agent !== "all") + Number(status !== "all") + Number(sentiment !== "all") + Number(Boolean(sessionQuery));
  const tabs = kind === "call" ? ["Base", "Post Call Analysis", "Metadata", "Dynamic Variables"] : ["Base", "Post Chat Analysis"];
  const fields = kind === "call" ? ["Agent", "Transfer Agent", "Call ID", "Batch Call ID", "Type", "Duration", "From", "To", "User Sentiment", "Disconnection Reason", "Call Status", "Call Successful"] : ["Agent", "Chat ID", "User Sentiment", "Disconnection Reason", "Chat Successful", "Chat Status"];

  function toggle(panel: Exclude<OpenPanel, null>) { setOpenPanel((current) => current === panel ? null : panel); }
  function clearFilters() { setAgent("all"); setStatus("all"); setSentiment("all"); setSessionQuery(""); setPage(1); }
  function exportRows() { downloadCsv(`${kind}-history.csv`, rows); setOpenPanel(null); }

  return <div ref={rootRef} className="glass relative min-h-[520px] rounded-2xl">
    <header className="rounded-t-2xl border-b border-[#dce2e8] bg-white/90 p-4">
      <h2 className="flex items-center gap-2 font-semibold"><RefreshCw className="size-4 text-[#667487]"/>{kind === "call" ? "Call" : "Chat"} History</h2>
      <div className="mt-4 flex flex-wrap items-center gap-3">
        <div className="relative">
          <button type="button" aria-expanded={openPanel === "filters"} onClick={() => toggle("filters")} className={`${control} flex items-center gap-2 px-4 ${openPanel === "filters" ? "border-[#4f647e] ring-4 ring-[#4f647e12]" : ""}`}><Filter className="size-4"/>Filter{activeFilters > 0 && <span className="grid size-5 place-items-center rounded-full bg-[#2d394b] text-[10px] font-bold text-white">{activeFilters}</span>}</button>
          {openPanel === "filters" && <Panel className="left-0 w-[min(90vw,520px)]"><div className="flex gap-5 overflow-x-auto border-b px-4 pt-4">{tabs.map((tab) => <button type="button" key={tab} onClick={() => setFilterTab(tab)} className={`whitespace-nowrap border-b-2 pb-3 text-sm ${filterTab === tab ? "border-[#253246] font-semibold text-[#253246]" : "border-transparent text-[#697789]"}`}>{tab}</button>)}</div>{filterTab === "Base" ? <div className="max-h-[430px] overflow-y-auto p-4"><div className="grid gap-3 sm:grid-cols-2"><FilterSelect label="Agent" value={agent} setValue={(value) => { setAgent(value); setPage(1); }} values={agents}/><FilterSelect label={`${kind === "call" ? "Call" : "Chat"} Status`} value={status} setValue={(value) => { setStatus(value); setPage(1); }} values={statuses}/><FilterSelect label="User Sentiment" value={sentiment} setValue={(value) => { setSentiment(value); setPage(1); }} values={sentiments}/><label className="text-xs font-semibold text-[#596a7a]">{kind === "call" ? "Call" : "Chat"} ID<input value={sessionQuery} onChange={(event) => { setSessionQuery(event.target.value); setPage(1); }} placeholder="Search exact or partial ID" className={`${control} mt-2 w-full`}/></label></div><div className="mt-5 border-t pt-4"><p className="mb-2 text-[11px] font-bold uppercase tracking-wider text-[#84928d]">Available fields</p><div className="grid gap-1 sm:grid-cols-2">{fields.map((field) => <div key={field} className="flex items-center gap-2 rounded-lg px-2 py-1.5 text-xs text-[#596a7a]"><CirclePlus className="size-3.5"/>{field}</div>)}</div></div></div> : <div className="grid min-h-56 place-items-center p-8 text-center text-sm text-[#84928d]">No synchronized custom fields are available for this category.</div>}<footer className="flex items-center justify-between border-t p-4"><button type="button" onClick={clearFilters} disabled={!activeFilters} className="text-sm font-semibold text-[#667487] disabled:opacity-35">Clear all</button><button type="button" onClick={() => setOpenPanel(null)} className="rounded-xl bg-[#2d394b] px-5 py-2.5 text-sm font-semibold text-white">Apply filters</button></footer></Panel>}
        </div>
        <div className="relative ml-auto"><button type="button" aria-label="Manage columns" aria-expanded={openPanel === "columns"} onClick={() => toggle("columns")} className={`${control} grid w-11 place-items-center px-0 ${openPanel === "columns" ? "border-[#4f647e] ring-4 ring-[#4f647e12]" : ""}`}><Settings2 className="size-4"/></button>{openPanel === "columns" && <Panel className="right-0 w-56 p-3"><p className="px-2 pb-2 text-[11px] font-bold uppercase tracking-wider text-[#84928d]">Visible columns</p>{Object.keys(visible).filter((column) => kind === "chat" || !["from", "to"].includes(column)).map((column) => <label key={column} className="flex cursor-pointer items-center gap-3 rounded-lg px-2 py-2 text-sm hover:bg-[#f2f4f7]"><input type="checkbox" checked={visible[column]} onChange={() => setVisible((current) => ({ ...current, [column]: !current[column] }))} className="size-4 accent-[#2d394b]"/>{column === "session" ? "Session ID" : title(column)}</label>)}</Panel>}</div>
        <div className="relative"><button type="button" aria-expanded={openPanel === "actions"} onClick={() => toggle("actions")} className="flex h-11 items-center gap-2 rounded-xl bg-[#2d394b] px-4 text-sm font-semibold text-white shadow-sm hover:bg-[#3a485d]">Actions<ChevronDown className={`size-4 transition ${openPanel === "actions" ? "rotate-180" : ""}`}/></button>{openPanel === "actions" && <Panel className="right-0 w-56 p-2"><button type="button" onClick={exportRows} disabled={!rows.length} className="flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-left text-sm hover:bg-[#f2f4f7] disabled:opacity-40"><Check className="size-4"/>Export current view</button></Panel>}</div>
      </div>
    </header>
    <div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-left"><thead><tr className="bg-[#f1f3f5] text-xs text-[#596a7a]"><th className="p-4">Time</th>{visible.agent&&<th className="p-4">Agent</th>}{visible.duration&&<th className="p-4">Duration</th>}{visible.channel&&<th className="p-4">Channel Type</th>}{visible.session&&<th className="p-4">Session ID</th>}{visible.reason&&<th className="p-4">End Reason</th>}{visible.status&&<th className="p-4">Session Status</th>}{visible.sentiment&&<th className="p-4">User Sentiment</th>}{visible.from&&<th className="p-4">From</th>}{visible.to&&<th className="p-4">To</th>}</tr></thead><tbody>{shownRows.map((row) => <tr key={row.id} className="border-b border-[#dfe4e8] text-sm transition hover:bg-[#f7f9fb]"><td className="whitespace-nowrap p-4">{row.time}</td>{visible.agent&&<td className="p-4">{row.agent}</td>}{visible.duration&&<td className="p-4">{row.duration}</td>}{visible.channel&&<td className="p-4">{row.channel}</td>}{visible.session&&<td className="max-w-56 truncate p-4" title={row.id}>{row.id}</td>}{visible.reason&&<td className="p-4">{row.reason}</td>}{visible.status&&<td className="p-4 capitalize">{row.status}</td>}{visible.sentiment&&<td className="p-4">{row.sentiment}</td>}{visible.from&&<td className="p-4">{row.from}</td>}{visible.to&&<td className="p-4">{row.to}</td>}</tr>)}</tbody></table>{!shownRows.length && <div className="grid min-h-48 place-items-center border-b text-sm text-[#84928d]">No sessions match the current filters.</div>}</div>
    <footer className="flex flex-col gap-3 rounded-b-2xl bg-white/80 p-4 text-sm text-[#71817c] sm:flex-row sm:items-center"><span>Page {safePage} of {totalPages} • Total Sessions: {rows.length}</span><div className="flex items-center gap-2 sm:ml-auto"><button type="button" aria-label="Previous page" disabled={safePage <= 1} onClick={() => setPage((current) => Math.max(1, current - 1))} className="grid size-9 place-items-center rounded-lg border bg-white disabled:opacity-30"><ChevronLeft className="size-4"/></button><span className="grid size-9 place-items-center rounded-lg bg-[#f1f3f7] font-semibold text-[#253246]">{safePage}</span><button type="button" aria-label="Next page" disabled={safePage >= totalPages} onClick={() => setPage((current) => Math.min(totalPages, current + 1))} className="grid size-9 place-items-center rounded-lg border bg-white disabled:opacity-30"><ChevronRight className="size-4"/></button><select value={pageSize} onChange={(event) => { setPageSize(Number(event.target.value)); setPage(1); }} aria-label="Rows per page" className="ml-2 h-9 rounded-lg border bg-white px-3"><option value={25}>25 / page</option><option value={50}>50 / page</option><option value={100}>100 / page</option></select></div></footer>
  </div>;
}

function Panel({ className, children }: { className: string; children: React.ReactNode }) { return <div role="menu" className={`absolute top-[calc(100%+8px)] z-[100] overflow-hidden rounded-2xl border border-[#cad3de] bg-white text-[#253246] shadow-[0_20px_55px_rgba(35,49,67,.22)] ${className}`}>{children}</div>; }
function FilterSelect({ label, value, setValue, values }: { label: string; value: string; setValue: (value: string) => void; values: string[] }) { return <label className="text-xs font-semibold text-[#596a7a]">{label}<select value={value} onChange={(event) => setValue(event.target.value)} className={`${control} mt-2 w-full`}><option value="all">All</option>{values.map((item) => <option key={item} value={item}>{item}</option>)}</select></label>; }
function unique(values: string[]) { return Array.from(new Set(values)).sort(); }
function title(value: string) { return value.charAt(0).toUpperCase() + value.slice(1); }
function downloadCsv(filename: string, rows: Row[]) { const first = rows[0]; if (!first) return; const keys = Object.keys(first) as Array<keyof Row>; const csv = [keys.join(","), ...rows.map((row) => keys.map((key) => JSON.stringify(row[key] ?? "")).join(","))].join("\n"); const url = URL.createObjectURL(new Blob([csv], { type: "text/csv" })); const link = document.createElement("a"); link.href = url; link.download = filename; link.click(); URL.revokeObjectURL(url); }
